"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Loader2, MessageCircle, Reply, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { createTaskCommentAction, deleteTaskCommentAction, loadTaskCommentsAction, updateTaskCommentAction } from "@/app/(app)/projects/[projectId]/todos/comment-actions";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { TaskAssigneeOption } from "@/domain/tasks/read";
import type { TaskCommentAudience, TaskCommentView } from "@/domain/task-comments/schemas";
import { requireActionSuccess, useOptimisticMutations } from "@/hooks/use-optimistic-mutations";

const CHANNEL = "time-log-task-comments";
const audienceLabels: Record<TaskCommentAudience, string> = { project_team: "Project team", assignees: "Task assignees", selected: "Selected people", private: "Private", client_visible: "Client-visible" };
const initials = (name: string) => name.split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("") || "?";

type Discussion = NonNullable<Awaited<ReturnType<typeof import("@/domain/task-comments/read").readTaskComments>>>;

export function TaskComments({ projectId, taskId, taskVisibility, participants, readOnly, archived, clientView, discussionWritable }: { projectId: string; taskId: string; taskVisibility: "internal" | "client-visible"; participants: TaskAssigneeOption[]; readOnly: boolean; archived: boolean; clientView: boolean; discussionWritable: boolean }) {
  const mutations = useOptimisticMutations(); const [discussion, setDiscussion] = useState<Discussion | null>(null); const [loading, setLoading] = useState(true); const [body, setBody] = useState(""); const [audience, setAudience] = useState<TaskCommentAudience>(clientView ? "client_visible" : "project_team"); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [mentionedIds, setMentionedIds] = useState<string[]>([]); const [replyTo, setReplyTo] = useState<TaskCommentView | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [editingBody, setEditingBody] = useState(""); const [deleteTarget, setDeleteTarget] = useState<TaskCommentView | null>(null);
  const load = useCallback(async (quiet = false) => { if (!quiet) setLoading(true); const result = await loadTaskCommentsAction(projectId, taskId); if (result.ok && result.data) setDiscussion(result.data); else if (!quiet) toast.error(result.ok ? "Discussion unavailable." : result.error); if (!quiet) setLoading(false); }, [projectId, taskId]);
  useEffect(() => { queueMicrotask(() => void load()); const channel = typeof BroadcastChannel === "undefined" ? null : new BroadcastChannel(CHANNEL); const onMessage = (event: MessageEvent<{ projectId?: string; taskId?: string }>) => { if (event.data?.projectId === projectId && event.data.taskId === taskId) void load(true); }; channel?.addEventListener("message", onMessage); return () => { channel?.removeEventListener("message", onMessage); channel?.close(); }; }, [load, projectId, taskId]);
  const publish = () => { if (typeof BroadcastChannel === "undefined") return; const channel = new BroadcastChannel(CHANNEL); channel.postMessage({ projectId, taskId }); channel.close(); };
  const roots = useMemo(() => discussion?.comments.filter((comment) => !comment.parentCommentId) ?? [], [discussion]);
  const replies = (rootId: string) => discussion?.comments.filter((comment) => comment.rootCommentId === rootId) ?? [];

  const submit = () => {
    if (!discussion || !body.trim()) return; if (audience === "selected" && !selectedIds.length && !replyTo) { toast.error("Choose at least one person."); return; }
    const optimisticId = `pending-${crypto.randomUUID()}`; const now = new Date().toISOString(); const effectiveAudience = replyTo?.audience ?? audience; const effectiveSelected = replyTo?.audienceUserIds ?? (effectiveAudience === "selected" ? selectedIds : []); const allowedMentions = new Set(mentionPeople.map((person) => person.id));
    const optimistic: TaskCommentView = { id: optimisticId, taskId, body: body.trim(), authorId: discussion.viewer.userId, authorName: discussion.viewer.name, audienceOwnerId: replyTo?.audienceOwnerId ?? discussion.viewer.userId, parentCommentId: replyTo?.id ?? null, rootCommentId: replyTo ? (replyTo.rootCommentId ?? replyTo.id) : null, audience: effectiveAudience, audienceUserIds: effectiveSelected, mentionedUserIds: mentionedIds.filter((id) => allowedMentions.has(id)), createdAt: now, updatedAt: now, editedAt: null, deletedAt: null, deletedBy: null, canEdit: true, canDelete: true };
    const previousBody = body; setBody(""); setReplyTo(null); setMentionedIds([]);
    void mutations.run({ scope: `task-comment:${optimisticId}`, operation: "create", snapshot: () => null, optimistic: () => setDiscussion((current) => current ? { ...current, comments: [...current.comments, optimistic] } : current), request: async () => requireActionSuccess(await createTaskCommentAction(projectId, { taskId, parentCommentId: optimistic.parentCommentId, body: optimistic.body, audience: optimistic.audience, audienceUserIds: optimistic.audienceUserIds, mentionedUserIds: optimistic.mentionedUserIds })), reconcile: (result) => { setDiscussion((current) => current ? { ...current, comments: current.comments.map((comment) => comment.id === optimisticId ? { ...comment, id: result.id } : comment) } : current); publish(); }, rollback: () => { setDiscussion((current) => current ? { ...current, comments: current.comments.filter((comment) => comment.id !== optimisticId) } : current); setBody(previousBody); }, errorMessage: () => "The comment could not be posted.", onError: (message) => toast.error(message), retry: true });
  };
  const saveEdit = (comment: TaskCommentView) => { const previous = comment; const nextBody = editingBody.trim(); if (!nextBody) return; setEditingId(null); setDiscussion((current) => current ? { ...current, comments: current.comments.map((item) => item.id === comment.id ? { ...item, body: nextBody, editedAt: new Date().toISOString() } : item) } : current); void mutations.run({ scope: `task-comment:${comment.id}`, operation: "edit", snapshot: () => previous, optimistic: () => undefined, request: async () => requireActionSuccess(await updateTaskCommentAction(projectId, { taskId, commentId: comment.id, body: nextBody, mentionedUserIds: comment.mentionedUserIds })), reconcile: () => publish(), rollback: (snapshot) => setDiscussion((current) => current ? { ...current, comments: current.comments.map((item) => item.id === snapshot.id ? snapshot : item) } : current), errorMessage: () => "The comment could not be edited.", onError: (message) => toast.error(message), retry: true }); };
  const remove = (comment: TaskCommentView) => { const previous = comment; setDeleteTarget(null); setDiscussion((current) => current ? { ...current, comments: current.comments.map((item) => item.id === comment.id ? { ...item, body: "", deletedAt: new Date().toISOString(), canEdit: false, canDelete: false } : item) } : current); void mutations.run({ scope: `task-comment:${comment.id}`, operation: "delete", snapshot: () => previous, optimistic: () => undefined, request: async () => requireActionSuccess(await deleteTaskCommentAction(projectId, { taskId, commentId: comment.id })), reconcile: () => publish(), rollback: (snapshot) => setDiscussion((current) => current ? { ...current, comments: current.comments.map((item) => item.id === snapshot.id ? snapshot : item) } : current), errorMessage: () => "The comment could not be deleted.", onError: (message) => toast.error(message), retry: true }); };

  const row = (comment: TaskCommentView, nested = false) => <div key={comment.id} id={`task-comment-${comment.id}`} className={nested ? "ml-7 border-l pl-4" : ""}><div className="flex gap-3 py-3"><Avatar size="sm"><AvatarFallback>{initials(comment.authorName)}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="text-sm font-medium">{comment.authorName}</span><span className="text-xs text-muted-foreground">{new Date(comment.createdAt).toLocaleString()}{comment.editedAt ? " · Edited" : ""}{comment.id.startsWith("pending-") ? " · Saving…" : ""}</span><span className="rounded-full bg-muted px-2 py-0.5 text-[11px] text-muted-foreground">{audienceLabels[comment.audience]}</span></div>{comment.deletedAt ? <p className="mt-1 text-sm italic text-muted-foreground">Comment deleted</p> : editingId === comment.id ? <div className="mt-2 space-y-2"><Textarea value={editingBody} onChange={(event) => setEditingBody(event.target.value)} maxLength={5000} /><div className="flex gap-2"><Button size="sm" onClick={() => saveEdit(comment)}>Save</Button><Button size="sm" variant="outline" onClick={() => setEditingId(null)}>Cancel</Button></div></div> : <p className="mt-1 whitespace-pre-wrap text-sm">{comment.body}</p>}{!comment.deletedAt && !comment.id.startsWith("pending-") && <div className="mt-2 flex flex-wrap gap-1"><Button size="xs" variant="ghost" onClick={() => { setReplyTo(comment); setBody(""); }}><Reply /> Reply</Button>{comment.canEdit && <Button size="xs" variant="ghost" onClick={() => { setEditingId(comment.id); setEditingBody(comment.body); }}>Edit</Button>}{comment.canDelete && <Button size="xs" variant="ghost" onClick={() => setDeleteTarget(comment)}><Trash2 /> Delete</Button>}</div>}</div></div></div>;

  if (loading) return <div className="flex items-center gap-2 py-4 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" /> Loading discussion…</div>;
  if (!discussion) return <p className="py-4 text-sm text-muted-foreground">Discussion is unavailable.</p>;
  const canPost = discussionWritable && !archived && (!readOnly || clientView);
  const composerAudience = replyTo?.audience ?? audience;
  const composerSelectedIds = replyTo?.audienceUserIds ?? selectedIds;
  const mentionPeople = composerAudience === "private" ? [] : composerAudience === "assignees" ? participants.filter((person) => discussion.task.assigneeIds.includes(person.id)) : composerAudience === "selected" ? participants.filter((person) => composerSelectedIds.includes(person.id)) : participants;
  return <section className="mt-5 border-t pt-4"><div className="mb-3 flex items-center gap-2"><MessageCircle className="size-4" /><h3 className="font-medium">Comments ({discussion.comments.filter((comment) => !comment.deletedAt).length})</h3></div><div className="divide-y">{roots.length ? roots.map((root) => <div key={root.id}>{row(root)}{replies(root.id).map((reply) => row(reply, true))}</div>) : <p className="py-4 text-sm text-muted-foreground">No comments yet.</p>}</div>{canPost && <div className="mt-4 space-y-3 rounded-lg border bg-background p-3">{replyTo && <div className="flex items-center justify-between gap-2 text-xs text-muted-foreground"><span>Replying to {replyTo.authorName} · {audienceLabels[replyTo.audience]}</span><Button size="xs" variant="ghost" onClick={() => setReplyTo(null)}>Cancel reply</Button></div>}<Textarea placeholder={replyTo ? "Write a reply…" : "Add to the discussion…"} value={body} onChange={(event) => setBody(event.target.value)} maxLength={5000} />{!replyTo && !clientView && <div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Who can see this?</Label><Select value={audience} onValueChange={(value) => setAudience(value as TaskCommentAudience)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="project_team">Project team</SelectItem><SelectItem value="assignees">Task assignees</SelectItem><SelectItem value="selected">Selected people</SelectItem><SelectItem value="private">Private to me and admins</SelectItem>{taskVisibility === "client-visible" && <SelectItem value="client_visible">Client-visible</SelectItem>}</SelectContent></Select></div></div>}{!replyTo && audience === "selected" && <PeoplePicker label="Visible to" people={participants} values={selectedIds} onChange={setSelectedIds} />}{!clientView && mentionPeople.some((person) => person.id !== discussion.viewer.userId) && <PeoplePicker label="Notify people" people={mentionPeople.filter((person) => person.id !== discussion.viewer.userId)} values={mentionedIds} onChange={setMentionedIds} />}<div className="flex justify-end"><Button onClick={submit} disabled={!body.trim()}><Send />{replyTo ? "Reply" : "Comment"}</Button></div></div>}
      <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => !open && setDeleteTarget(null)}><DialogContent><DialogHeader><DialogTitle>Delete comment?</DialogTitle><DialogDescription>The content will be removed, while an audited placeholder preserves the thread.</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="outline">Cancel</Button></DialogClose><Button variant="destructive" onClick={() => deleteTarget && remove(deleteTarget)}>Delete</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}

function PeoplePicker({ label, people, values, onChange }: { label: string; people: TaskAssigneeOption[]; values: string[]; onChange(values: string[]): void }) { return <fieldset className="space-y-2"><legend className="text-sm font-medium">{label}</legend><div className="grid gap-2 sm:grid-cols-2">{people.map((person) => <label key={person.id} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Checkbox checked={values.includes(person.id)} onCheckedChange={(checked) => onChange(checked ? [...new Set([...values, person.id])] : values.filter((id) => id !== person.id))} /><span className="min-w-0 truncate">{person.name}</span></label>)}</div></fieldset>; }
