"use client";
import Link from "next/link";
import { FormEvent, useState, useTransition } from "react";
import { Archive, Bell, MessageSquare, Pin, PinOff, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { archiveCommentAction, changePostVisibilityAction, createCommentAction, createPostAction, setArchivedAction, setPinnedAction, updateCommentAction, updatePostAction } from "@/app/(app)/projects/[projectId]/messages/actions";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { VisibilityBadge } from "@/components/visibility/visibility-badge";
import type { MessageBoardPost } from "@/domain/messages/schemas";

type Viewer = { userId: string; role: "admin" | "member" | "client" };
export function MessageBoard({ projectId, initialPosts, viewer, canCreatePosts, canModerate, archived, nextCursor }: { projectId: string; initialPosts: MessageBoardPost[]; viewer: Viewer; canCreatePosts: boolean; canModerate: boolean; archived: boolean; nextCursor: string | null }) {
  const posts = initialPosts; const [pending, startTransition] = useTransition(); const [editing, setEditing] = useState<string | null>(null); const [editingComment, setEditingComment] = useState<string | null>(null);
  const run = (operation: () => Promise<{ ok: true; data: unknown } | { ok: false; error: string }>, done?: () => void) => startTransition(async () => { const result = await operation(); if (!result.ok) toast.error(result.error); else { done?.(); window.location.reload(); } });
  function submitPost(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); run(() => createPostAction(projectId, { title: data.get("title"), body: data.get("body"), visibility: data.get("visibility"), emailAnnouncement: data.get("emailAnnouncement") === "on" }), () => toast.success("Post published.")); }
  return <div className="space-y-6">
    <div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Message board</h2><p className="text-sm text-muted-foreground">Durable announcements and project updates.</p></div>{viewer.role !== "client" && <Button asChild variant="outline"><Link href={archived ? `/projects/${projectId}/messages` : `/projects/${projectId}/messages?archived=1`}>{archived ? <MessageSquare /> : <Archive />}{archived ? "Active posts" : "Archived"}</Link></Button>}</div>
    {canCreatePosts && !archived && <form onSubmit={submitPost} className="space-y-4 rounded-xl border bg-card p-4"><div className="grid gap-4 sm:grid-cols-[1fr_12rem]"><div className="space-y-2"><Label htmlFor="post-title">Title</Label><Input id="post-title" name="title" maxLength={180} required /></div><div className="space-y-2"><Label>Visibility</Label><Select name="visibility" defaultValue="internal"><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="internal">Internal</SelectItem><SelectItem value="client-visible">Client-visible</SelectItem></SelectContent></Select></div></div><div className="space-y-2"><Label htmlFor="post-body">Update</Label><Textarea id="post-body" name="body" maxLength={10000} required rows={5} /></div>{canModerate && <label className="flex items-start gap-3 rounded-lg border bg-muted/20 p-3"><Checkbox name="emailAnnouncement" /><span><span className="flex items-center gap-2 text-sm font-medium"><Bell className="size-4" />Email this announcement</span><span className="mt-1 block text-xs text-muted-foreground">Sends once to eligible assigned recipients after publishing.</span></span></label>}<Button disabled={pending}>{pending ? "Publishing…" : "Publish update"}</Button></form>}
    {posts.length === 0 ? <div className="rounded-xl border bg-muted/20 p-10 text-center"><MessageSquare className="mx-auto mb-3 size-8 text-muted-foreground" /><p className="font-medium">{archived ? "No archived posts" : "No updates yet"}</p></div> : <div className="space-y-4">{posts.map((post) => { const owns = post.authorId === viewer.userId; return <article id={`post-${post.id}`} key={post.id} className="rounded-xl border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2">{post.pinnedAt && <Pin className="size-4 text-primary" />}<h3 className="text-lg font-semibold">{post.title}</h3><VisibilityBadge visibility={post.visibility} />{post.announcement && <span className="text-xs text-muted-foreground">Announcement</span>}</div><p className="mt-1 text-xs text-muted-foreground">{post.authorName} · {new Date(post.createdAt).toLocaleString()}{post.editedAt ? " · Edited" : ""}</p></div><div className="flex flex-wrap gap-2">{!archived && canModerate && <Button size="sm" variant="ghost" onClick={() => run(() => setPinnedAction(projectId, post.id, !post.pinnedAt))}>{post.pinnedAt ? <PinOff /> : <Pin />}{post.pinnedAt ? "Unpin" : "Pin"}</Button>}{!archived && (owns || canModerate) && <Button size="sm" variant="ghost" onClick={() => setEditing(editing === post.id ? null : post.id)}>Edit</Button>}{!archived && (owns || canModerate) && <Button size="sm" variant="ghost" onClick={() => run(() => setArchivedAction(projectId, post.id, true))}><Archive />Archive</Button>}{archived && (owns || canModerate) && <Button size="sm" variant="outline" onClick={() => run(() => setArchivedAction(projectId, post.id, false))}><RotateCcw />Restore</Button>}</div></div>
      {editing === post.id ? <form className="mt-4 space-y-3" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); run(() => updatePostAction(projectId, { postId: post.id, title: data.get("title"), body: data.get("body") }), () => setEditing(null)); }}><Input name="title" defaultValue={post.title} required maxLength={180} /><Textarea name="body" defaultValue={post.body} required maxLength={10000} rows={5} /><div className="flex gap-2"><Button size="sm" disabled={pending}>Save</Button><Button size="sm" type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button></div></form> : <p className="mt-4 whitespace-pre-wrap text-sm leading-6">{post.body}</p>}
      {!archived && viewer.role !== "client" && (owns || canModerate) && <div className="mt-4 max-w-48"><Select value={post.visibility} onValueChange={(value) => run(() => changePostVisibilityAction(projectId, post.id, value))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="internal">Internal</SelectItem><SelectItem value="client-visible">Client-visible</SelectItem></SelectContent></Select></div>}
      {!archived && <div className="mt-5 border-t pt-4"><div className="space-y-3">{post.comments.map((comment) => { const canEdit = comment.authorId === viewer.userId || canModerate; return <div key={comment.id} className="rounded-lg bg-muted/30 p-3"><div className="flex justify-between gap-3"><p className="text-xs text-muted-foreground">{comment.authorName} · {new Date(comment.createdAt).toLocaleString()}{comment.editedAt ? " · Edited" : ""}</p>{canEdit && <div className="flex gap-1"><Button size="xs" variant="ghost" onClick={() => setEditingComment(editingComment === comment.id ? null : comment.id)}>Edit</Button><Button size="xs" variant="ghost" onClick={() => run(() => archiveCommentAction(projectId, post.id, comment.id))}>Archive</Button></div>}</div>{editingComment === comment.id ? <form className="mt-2 flex gap-2" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); run(() => updateCommentAction(projectId, { postId: post.id, commentId: comment.id, body: data.get("body") }), () => setEditingComment(null)); }}><Input name="body" defaultValue={comment.body} required maxLength={5000} /><Button size="sm">Save</Button></form> : <p className="mt-1 whitespace-pre-wrap text-sm">{comment.body}</p>}</div>})}</div><form className="mt-3 flex gap-2" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); run(() => createCommentAction(projectId, { postId: post.id, body: data.get("body") }), () => form.reset()); }}><Input name="body" placeholder="Write a comment" required maxLength={5000} /><Button variant="outline" disabled={pending}>Comment</Button></form></div>}
    </article>; })}</div>}
    {nextCursor && <div className="flex justify-center"><Button asChild variant="outline"><Link href={`/projects/${projectId}/messages?${archived ? "archived=1&" : ""}before=${encodeURIComponent(nextCursor)}`}>Older posts</Link></Button></div>}
  </div>;
}
