import "server-only";
import { createHash } from "node:crypto";
import { FieldValue, type Firestore, type Transaction } from "firebase-admin/firestore";
import { executeAuditedCommand, AuditedCommandError, type AuditWriter } from "@/domain/audit/command";
import type { AuditCorrelation } from "@/domain/audit/correlation";
import { canAccessProject } from "@/domain/organizations/policy";
import { organizationMemberSchema, organizationSchema, projectAssignmentSchema, projectSchema } from "@/domain/organizations/schemas";
import { createCommentCommandSchema, createPostCommandSchema, messageCommentSchema, messagePostSchema, messageTargetCommandSchema, commentTargetCommandSchema, updateCommentCommandSchema, updatePostCommandSchema } from "@/domain/messages/schemas";
import { deliverNotification } from "@/domain/notifications/outbox";
import type { AuthActor } from "@/lib/auth-server";
import { getAdminDb } from "@/lib/firebase-admin";
import { parseApplicationUrl } from "@/lib/resend-config";
import { visibilitySchema } from "@/domain/visibility/schemas";

type Dependencies = { db?: Firestore; auditRepository?: AuditWriter; deliver?: typeof deliverNotification };
const base = (org: string, project: string) => `organizations/${org}/projects/${project}/messages`;
const actorName = (actor: AuthActor) => actor.displayName?.trim() || actor.email || "A teammate";

async function access(transaction: Transaction, db: Firestore, org: string, projectId: string, uid: string) {
  const [memberDoc, assignmentDoc, projectDoc, orgDoc] = await Promise.all([transaction.get(db.doc(`organizations/${org}/members/${uid}`)), transaction.get(db.doc(`organizations/${org}/projects/${projectId}/projectMembers/${uid}`)), transaction.get(db.doc(`organizations/${org}/projects/${projectId}`)), transaction.get(db.doc(`organizations/${org}`))]);
  const member = memberDoc.exists ? organizationMemberSchema.parse(memberDoc.data()) : null; const assignment = assignmentDoc.exists ? projectAssignmentSchema.parse(assignmentDoc.data()) : null;
  if (!canAccessProject(member, assignment)) throw new AuditedCommandError("denied", "message_access_denied", "Message board access denied");
  if (!projectDoc.exists || !orgDoc.exists) throw new AuditedCommandError("failed", "message_context_missing", "Project unavailable");
  const project = projectSchema.parse({ id: projectDoc.id, ...projectDoc.data() });
  if (project.status !== "active" || !project.enabledTools.includes("messages")) throw new AuditedCommandError("denied", "message_board_unavailable", "Message board is unavailable");
  return { member: member!, assignment, project, organization: organizationSchema.parse({ id: orgDoc.id, ...orgDoc.data() }), moderator: member!.role === "admin" || assignment?.projectRole === "admin" };
}

export async function createMessagePost(actor: AuthActor, org: string, projectId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) {
  const command = createPostCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.collection(base(org, projectId)).doc();
  const result = await executeAuditedCommand<{ notificationIds: string[] }>({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "message.post.created", target: { type: "message", id: ref.id }, correlation, changes: [{ field: "visibility", to: command.visibility }], additionalSuccessAudits: (value) => value.notificationIds.map((id) => ({ action: "notification.email.queued", target: { type: "notification", id }, changes: [{ field: "deliveryStatus", to: "queued" }] })), execute: async (transaction) => {
    const current = await access(transaction, db, org, projectId, actor.uid); if (current.member.role === "client") throw new AuditedCommandError("denied", "message_post_create_denied", "Clients cannot publish posts"); if (command.emailAnnouncement && !current.moderator) throw new AuditedCommandError("denied", "announcement_publish_denied", "Only project administrators can email announcements");
    const now = FieldValue.serverTimestamp(); const notificationIds: string[] = []; const notifications: Array<{ reference: FirebaseFirestore.DocumentReference; value: Record<string, unknown> }> = [];
    if (command.emailAnnouncement) {
      const assignments = await transaction.get(db.collection(`organizations/${org}/projects/${projectId}/projectMembers`).where("status", "==", "active").limit(201));
      if (assignments.size > 200) throw new AuditedCommandError("failed", "announcement_recipient_limit", "This announcement has too many recipients for one send");
      const memberDocs = await Promise.all(assignments.docs.map((assignmentDoc) => transaction.get(db.doc(`organizations/${org}/members/${assignmentDoc.id}`))));
      for (const memberDoc of memberDocs) {
        if (!memberDoc.exists) continue; const recipient = organizationMemberSchema.parse(memberDoc.data());
        if (recipient.status !== "active" || !recipient.email || recipient.userId === actor.uid || (recipient.role === "client" && command.visibility !== "client-visible")) continue;
        const key = createHash("sha256").update(`${ref.id}:${recipient.userId}`).digest("hex").slice(0, 40); const notificationRef = db.doc(`organizations/${org}/notifications/announcement-${key}`); notificationIds.push(notificationRef.id);
        notifications.push({ reference: notificationRef, value: { type: "announcement", recipientEmail: recipient.email, recipientUserId: recipient.userId, projectId, messageId: ref.id, templateData: { projectName: current.project.name, announcementTitle: command.title, authorName: actorName(actor), targetUrl: `${parseApplicationUrl(process.env)}/projects/${projectId}/messages#post-${ref.id}` }, status: "queued", idempotencyKey: `announcement/${ref.id}/${recipient.userId}`, providerMessageId: null, providerStatus: null, providerEventAt: null, attemptCount: 0, lastErrorCode: null, claimId: null, claimExpiresAt: null, nextAttemptAt: null, createdAt: now, updatedAt: now } });
      }
    }
    transaction.create(ref, { title: command.title, body: command.body, authorId: actor.uid, authorName: actorName(actor), visibility: command.visibility, announcement: command.emailAnnouncement, pinnedAt: null, pinnedBy: null, createdAt: now, updatedAt: now, editedAt: null, archivedAt: null });
    for (const notification of notifications) transaction.create(notification.reference, notification.value);
    return { notificationIds };
  }});
  await Promise.allSettled(result.notificationIds.map((id) => (dependencies.deliver ?? deliverNotification)(org, id, { db }))); return { id: ref.id };
}

export async function createMessageComment(actor: AuthActor, org: string, projectId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) {
  const command = createCommentCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.collection(`${base(org, projectId)}/${command.postId}/comments`).doc();
  return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "message.comment.created", target: { type: "comment", id: ref.id }, correlation, execute: async (transaction) => {
    const current = await access(transaction, db, org, projectId, actor.uid); const postDoc = await transaction.get(db.doc(`${base(org, projectId)}/${command.postId}`)); if (!postDoc.exists) throw new AuditedCommandError("failed", "message_post_not_found", "Post not found"); const post = messagePostSchema.parse({ id: postDoc.id, ...postDoc.data() });
    if (post.archivedAt || (current.member.role === "client" && post.visibility !== "client-visible")) throw new AuditedCommandError("denied", "message_comment_denied", "Commenting is unavailable"); const visibility = current.member.role === "client" ? "client-visible" : "internal";
    transaction.create(ref, { postId: post.id, body: command.body, authorId: actor.uid, authorName: actorName(actor), visibility, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp(), editedAt: null, archivedAt: null }); return { id: ref.id, visibility };
  }, changes: (result) => [{ field: "visibility", to: result.visibility }] });
}

export async function updateMessagePost(actor: AuthActor, org: string, projectId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const command = updatePostCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${command.postId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "message.post.updated", target: { type: "message", id: command.postId }, correlation, execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); const snap = await transaction.get(ref); const post = snap.exists ? messagePostSchema.parse({ id: snap.id, ...snap.data() }) : null; if (!post || post.archivedAt || (post.authorId !== actor.uid && !current.moderator)) throw new AuditedCommandError("denied", "message_post_edit_denied", "Post editing denied"); transaction.update(ref, { title: command.title, body: command.body, editedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); } }); }

export async function updateMessageComment(actor: AuthActor, org: string, projectId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const command = updateCommentCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${command.postId}/comments/${command.commentId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "message.comment.updated", target: { type: "comment", id: command.commentId }, correlation, execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); const snap = await transaction.get(ref); const comment = snap.exists ? messageCommentSchema.parse({ id: snap.id, ...snap.data() }) : null; if (!comment || comment.archivedAt || (comment.authorId !== actor.uid && !current.moderator)) throw new AuditedCommandError("denied", "message_comment_edit_denied", "Comment editing denied"); transaction.update(ref, { body: command.body, editedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); } }); }

export async function setMessagePinned(actor: AuthActor, org: string, projectId: string, raw: unknown, pinned: boolean, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const command = messageTargetCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${command.postId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: pinned ? "message.post.pinned" : "message.post.unpinned", target: { type: "message", id: command.postId }, correlation, changes: [{ field: "enabled", to: pinned }], execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); if (!current.moderator) throw new AuditedCommandError("denied", "message_pin_denied", "Pinning denied"); const snap = await transaction.get(ref); if (!snap.exists || snap.data()?.archivedAt) throw new AuditedCommandError("failed", "message_post_not_found", "Post not found"); transaction.update(ref, { pinnedAt: pinned ? FieldValue.serverTimestamp() : null, pinnedBy: pinned ? actor.uid : null, updatedAt: FieldValue.serverTimestamp() }); } }); }

export async function setMessageArchived(actor: AuthActor, org: string, projectId: string, raw: unknown, archived: boolean, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const command = messageTargetCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${command.postId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: archived ? "message.post.archived" : "message.post.restored", target: { type: "message", id: command.postId }, correlation, changes: [{ field: "status", to: archived ? "archived" : "active" }], execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); const snap = await transaction.get(ref); const post = snap.exists ? messagePostSchema.parse({ id: snap.id, ...snap.data() }) : null; if (!post || (post.authorId !== actor.uid && !current.moderator)) throw new AuditedCommandError("denied", "message_archive_denied", "Post archive denied"); transaction.update(ref, { archivedAt: archived ? FieldValue.serverTimestamp() : null, pinnedAt: archived ? null : post.pinnedAt, pinnedBy: archived ? null : post.pinnedBy, updatedAt: FieldValue.serverTimestamp() }); } }); }

export async function archiveMessageComment(actor: AuthActor, org: string, projectId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const command = commentTargetCommandSchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${command.postId}/comments/${command.commentId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "message.comment.archived", target: { type: "comment", id: command.commentId }, correlation, changes: [{ field: "status", to: "archived" }], execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); const snap = await transaction.get(ref); const comment = snap.exists ? messageCommentSchema.parse({ id: snap.id, ...snap.data() }) : null; if (!comment || (comment.authorId !== actor.uid && !current.moderator)) throw new AuditedCommandError("denied", "message_comment_archive_denied", "Comment archive denied"); transaction.update(ref, { archivedAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); } }); }

export async function changeMessageVisibility(actor: AuthActor, org: string, projectId: string, postId: string, raw: unknown, correlation: AuditCorrelation, dependencies: Dependencies = {}) { const visibility = visibilitySchema.parse(raw); const db = dependencies.db ?? getAdminDb(); const ref = db.doc(`${base(org, projectId)}/${postId}`); return executeAuditedCommand({ db, auditRepository: dependencies.auditRepository, organizationId: org, projectId, actor: { type: "user", id: actor.uid, role: null }, action: "visibility.record.changed", target: { type: "message", id: postId }, correlation, changes: [{ field: "visibility", to: visibility }], execute: async (transaction) => { const current = await access(transaction, db, org, projectId, actor.uid); const snap = await transaction.get(ref); const post = snap.exists ? messagePostSchema.parse({ id: snap.id, ...snap.data() }) : null; if (!post || post.archivedAt || current.member.role === "client" || (post.authorId !== actor.uid && !current.moderator)) throw new AuditedCommandError("denied", "message_visibility_denied", "Visibility change denied"); transaction.update(ref, { visibility, updatedAt: FieldValue.serverTimestamp() }); } }); }
