"use client";

import { useState, useTransition } from "react";
import { Loader2 } from "lucide-react";
import { changeMemberRoleAction, changeProjectAssignmentAction } from "@/app/(app)/admin/actions";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Project = { id: string; name: string; status: string; clientId: string | null };

export function MemberAdminControls({ userId, role, status, clientId, projects, assignedProjectIds }: { userId: string; role: "admin" | "member" | "client"; status: string; clientId: string | null; projects: Project[]; assignedProjectIds: string[] }) {
  const [pending, startTransition] = useTransition(); const [error, setError] = useState<string | null>(null); const [confirmation, setConfirmation] = useState<{ kind: "role" | "remove"; projectId?: string; role?: "admin" | "member" } | null>(null);
  if (status !== "active") return null;
  const applyRole = (nextRole: "admin" | "member") => startTransition(async () => { setError(null); const result = await changeMemberRoleAction({ userId, role: nextRole }); if (result.ok) setConfirmation(null); else setError(result.error); });
  const changeAssignment = (projectId: string, action: "assign" | "remove") => startTransition(async () => { setError(null); const result = await changeProjectAssignmentAction({ userId, projectId, action }); if (result.ok) setConfirmation(null); else setError(result.error); });
  const eligible = projects.filter((project) => role !== "client" || (clientId && project.clientId === clientId));
  return <div className="space-y-3 border-t pt-3">{role !== "client" && <div className="flex items-center gap-3"><span className="text-sm text-muted-foreground">Role</span><Select value={role} disabled={pending} onValueChange={(value: "admin" | "member") => role === "admin" && value === "member" ? setConfirmation({ kind: "role", role: value }) : applyRole(value)}><SelectTrigger className="w-36"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="member">Member</SelectItem><SelectItem value="admin">Admin</SelectItem></SelectContent></Select></div>}{role !== "admin" && <div><p className="mb-2 text-sm text-muted-foreground">Project access</p><div className="flex flex-wrap gap-2">{eligible.length === 0 ? <span className="text-sm text-muted-foreground">No eligible active projects.</span> : eligible.map((project) => { const assigned = assignedProjectIds.includes(project.id); return <Button key={project.id} size="sm" variant={assigned ? "secondary" : "outline"} disabled={pending || (!assigned && project.status === "archived")} onClick={() => assigned ? setConfirmation({ kind: "remove", projectId: project.id }) : changeAssignment(project.id, "assign")}>{assigned ? `Remove ${project.name}` : `Add ${project.name}`}</Button>; })}</div></div>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Dialog open={confirmation !== null} onOpenChange={(next) => !pending && !next && setConfirmation(null)}><DialogContent><DialogHeader><DialogTitle>{confirmation?.kind === "role" ? "Remove administrator role?" : "Remove project access?"}</DialogTitle><DialogDescription>{confirmation?.kind === "role" ? "This person will lose organization administration capabilities. The final active admin cannot be demoted." : "Access ends immediately. Historical tasks, time entries, and audit attribution remain unchanged."}</DialogDescription></DialogHeader>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<DialogFooter><Button variant="outline" disabled={pending} onClick={() => setConfirmation(null)}>Cancel</Button><Button variant="destructive" disabled={pending} onClick={() => confirmation?.kind === "role" ? applyRole(confirmation.role!) : changeAssignment(confirmation!.projectId!, "remove")}>{pending && <Loader2 className="animate-spin" />}{pending ? "Saving…" : "Confirm"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
