export const AUDIT_ACTIONS = [
  "auth.login.succeeded",
  "auth.login.failed",
  "auth.logout.succeeded",
  "auth.logout.failed",
  "organization.bootstrap.completed",
  "organization.onboarding.profile.saved",
  "organization.onboarding.organization.saved",
  "organization.onboarding.project.saved",
  "organization.onboarding.completed",
  "organization.invitation.created",
  "organization.invitation.accepted",
  "organization.invitation.revoked",
  "organization.client.created",
  "organization.membership.role.changed",
  "organization.membership.suspended",
  "organization.membership.restored",
  "organization.membership.removed",
  "project.record.created",
  "project.record.updated",
  "project.record.archived",
  "visibility.record.changed",
  "task.record.created",
  "task.record.updated",
  "task.record.completed",
  "task.record.reopened",
  "task.record.archived",
  "task.record.restored",
  "task.legacymigration.executed",
  "time.timer.started",
  "time.timer.stopped",
  "time.entry.created",
  "time.entry.corrected",
  "time.report.previewed",
  "time.report.exported",
  "file.record.uploaded",
  "file.record.downloaded",
  "file.record.deleted",
  "notification.email.queued",
  "notification.email.sent",
  "notification.email.failed",
  "approval.request.created",
  "approval.request.approved",
  "approval.request.rejected",
  "approval.request.executed",
  "connector.action.executed",
  "connector.action.failed",
  "agent.run.started",
  "agent.run.completed",
  "agent.run.failed",
  "agent.action.proposed",
  "agent.action.executed",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const SAFE_AUDIT_FIELDS = [
  "role",
  "status",
  "visibility",
  "billable",
  "enabled",
  "outcome",
  "projectStatus",
  "membershipStatus",
  "clientReportingStatus",
  "deliveryStatus",
  "approvalStatus",
  "organizationCreated",
  "membershipCreated",
  "selectionCreated",
  "migrationMarkerCreated",
  "onboardingStep",
  "onboardingCompleted",
  "projectCreated",
] as const;

export type SafeAuditField = (typeof SAFE_AUDIT_FIELDS)[number];

const NONE = [] as const;
const STATUS = ["status"] as const;

export const AUDIT_CHANGE_ALLOWLIST = {
  "auth.login.succeeded": NONE,
  "auth.login.failed": NONE,
  "auth.logout.succeeded": NONE,
  "auth.logout.failed": NONE,
  "organization.bootstrap.completed": ["organizationCreated", "membershipCreated", "selectionCreated", "migrationMarkerCreated"] as const,
  "organization.onboarding.profile.saved": ["onboardingStep"] as const,
  "organization.onboarding.organization.saved": ["onboardingStep"] as const,
  "organization.onboarding.project.saved": ["onboardingStep", "projectCreated"] as const,
  "organization.onboarding.completed": ["onboardingStep", "onboardingCompleted"] as const,
  "organization.invitation.created": ["role", "status"] as const,
  "organization.invitation.accepted": STATUS,
  "organization.invitation.revoked": STATUS,
  "organization.client.created": STATUS,
  "organization.membership.role.changed": ["role"] as const,
  "organization.membership.suspended": ["membershipStatus"] as const,
  "organization.membership.restored": ["membershipStatus"] as const,
  "organization.membership.removed": ["membershipStatus"] as const,
  "project.record.created": ["projectStatus"] as const,
  "project.record.updated": ["projectStatus", "enabled"] as const,
  "project.record.archived": ["projectStatus"] as const,
  "visibility.record.changed": ["visibility"] as const,
  "task.record.created": ["status", "visibility"] as const,
  "task.record.updated": ["status", "visibility"] as const,
  "task.record.completed": STATUS,
  "task.record.reopened": STATUS,
  "task.record.archived": STATUS,
  "task.record.restored": STATUS,
  "task.legacymigration.executed": STATUS,
  "time.timer.started": NONE,
  "time.timer.stopped": NONE,
  "time.entry.created": ["billable", "clientReportingStatus"] as const,
  "time.entry.corrected": ["billable", "clientReportingStatus"] as const,
  "time.report.previewed": NONE,
  "time.report.exported": NONE,
  "file.record.uploaded": ["status", "visibility"] as const,
  "file.record.downloaded": NONE,
  "file.record.deleted": STATUS,
  "notification.email.queued": ["deliveryStatus"] as const,
  "notification.email.sent": ["deliveryStatus"] as const,
  "notification.email.failed": ["deliveryStatus"] as const,
  "approval.request.created": ["approvalStatus"] as const,
  "approval.request.approved": ["approvalStatus"] as const,
  "approval.request.rejected": ["approvalStatus"] as const,
  "approval.request.executed": ["approvalStatus"] as const,
  "connector.action.executed": ["outcome"] as const,
  "connector.action.failed": ["outcome"] as const,
  "agent.run.started": ["status"] as const,
  "agent.run.completed": ["status"] as const,
  "agent.run.failed": ["status"] as const,
  "agent.action.proposed": ["approvalStatus"] as const,
  "agent.action.executed": ["outcome"] as const,
} satisfies Record<AuditAction, readonly SafeAuditField[]>;
