import type { Notification } from "@/domain/notifications/schemas";

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const link = (href: string, label: string) => `<a href="${escapeHtml(href)}" style="display:inline-block;background:#18181b;color:#fff;padding:10px 16px;border-radius:8px;text-decoration:none">${escapeHtml(label)}</a>`;
const shell = (preview: string, body: string) => `<!doctype html><html><body style="margin:0;background:#f4f4f5;font-family:Arial,sans-serif;color:#18181b"><span style="display:none">${escapeHtml(preview)}</span><div style="max-width:560px;margin:32px auto;background:#fff;border:1px solid #e4e4e7;border-radius:12px;padding:32px"><div style="font-weight:700;margin-bottom:24px">Time Log</div>${body}<p style="margin-top:28px;color:#71717a;font-size:12px">Sent by Time Log.</p></div></body></html>`;

export type RenderedEmail = { subject: string; html: string; text: string };

export function renderNotification(notification: Notification): RenderedEmail {
  switch (notification.type) {
    case "invitation": { const data = notification.templateData; return { subject: `You’re invited to ${data.organizationName}`, html: shell(`Join ${data.organizationName}`, `<h1>You’re invited</h1><p>${escapeHtml(data.inviterName)} invited you to join ${escapeHtml(data.organizationName)}.</p>${link(data.acceptUrl, "Accept invitation")}`), text: `${data.inviterName} invited you to join ${data.organizationName} in Time Log.\n\nAccept invitation: ${data.acceptUrl}` }; }
    case "assignment": { const data = notification.templateData; return { subject: `New task: ${data.taskTitle}`, html: shell(`You were assigned ${data.taskTitle}`, `<h1>New task assignment</h1><p>${escapeHtml(data.assignedByName)} assigned you “${escapeHtml(data.taskTitle)}” in ${escapeHtml(data.projectName)}.</p>${link(data.taskUrl, "View task")}`), text: `${data.assignedByName} assigned you "${data.taskTitle}" in ${data.projectName}.\n\nView task: ${data.taskUrl}` }; }
    case "mention": { const data = notification.templateData; return { subject: `You were mentioned in ${data.projectName}`, html: shell(`Mention in ${data.projectName}`, `<h1>You were mentioned</h1><p>${escapeHtml(data.authorName)} mentioned you in ${escapeHtml(data.contextLabel)}.</p>${link(data.targetUrl, "View mention")}`), text: `${data.authorName} mentioned you in ${data.contextLabel}.\n\nView mention: ${data.targetUrl}` }; }
    case "reminder": { const data = notification.templateData; return { subject: `Reminder: ${data.itemTitle}`, html: shell(`Reminder for ${data.itemTitle}`, `<h1>Upcoming work</h1><p>${escapeHtml(data.itemTitle)} is due ${escapeHtml(data.dueLabel)} in ${escapeHtml(data.projectName)}.</p>${link(data.targetUrl, "View item")}`), text: `${data.itemTitle} is due ${data.dueLabel} in ${data.projectName}.\n\nView item: ${data.targetUrl}` }; }
    case "announcement": { const data = notification.templateData; return { subject: `${data.projectName}: ${data.announcementTitle}`, html: shell(data.announcementTitle, `<h1>${escapeHtml(data.announcementTitle)}</h1><p>Posted by ${escapeHtml(data.authorName)} in ${escapeHtml(data.projectName)}.</p>${link(data.targetUrl, "Read announcement")}`), text: `${data.announcementTitle}\nPosted by ${data.authorName} in ${data.projectName}.\n\nRead: ${data.targetUrl}` }; }
    case "digest": { const data = notification.templateData; return { subject: `${data.organizationName} ${data.periodLabel} digest`, html: shell(`${data.periodLabel} digest`, `<h1>${escapeHtml(data.periodLabel)} digest</h1><p>${escapeHtml(data.summary)}</p>${link(data.targetUrl, "Open Time Log")}`), text: `${data.organizationName} ${data.periodLabel} digest\n\n${data.summary}\n\nOpen Time Log: ${data.targetUrl}` }; }
  }
}
